<%@ Page Language="C#" AutoEventWireup="true" CodeFile="TermsAndConditions.aspx.cs" Inherits="TermsNCondition" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Terms and Conditions - XtremeK DEVELOPMENT Tracking System</title>
    <link href="CSS/XtremeKLogin.css" rel="stylesheet" type="text/css" />
	<style type="text/css"> 
		html,body,form 
        { 
			height: 100%;
		} 
	</style>
</head>
<body>
    <form id="form1" runat="server"  >
	<div class="page">

		<div class="form_wrapper">
			<div class="form_header"></div> 

			<div style="width: 480px;" class="form_center">

				<h1>Alarmas ABC Application Service Provider Agreement</h1>

				<textarea style="width: 480px" class="form_text_area" rows="20" class="">
	This Application Service Provider Agreement (“Agreement”) sets out the terms and conditions pursuant to which Alarmas ABC USA llc. (“Alarmas ABC”) will make the Alarmas ABC XtremeK Application Services (as defined herein) available on a hosted basis to you, the customer (“Customer”).
	BY USING THE Alarmas ABC XtremeK  APPLICATION SERVICES, CUSTOMER AGREES TO THE FOLLOWING TERMS AND CONDITIONS AND AGREES TO BE BOUND HEREBY:
	1. Alarmas ABC XtremeK Application Service
	(a) During the term of this Agreement and in accordance with the terms hereof, Alarmas ABC will provide Customer access to and use of the Alarmas ABC XtremeK Application Services and the software related thereto (the “Alarmas ABC Application Software”), and Alarmas ABC shall provide and Customer shall be entitled to receive such Support Services (as defined herein) and other related services that are provided for herein (such Alarmas ABC Application Software, access, use and services referred to, collectively, as the “Service” or the “Alarmas ABC Application Service”).
	(b) The Alarmas ABC Application Service consists of a hosted web enabled application, data access and storage, carrier interface(s), email interface. Customer is responsible for obtaining and maintaining all computer hardware, software and communications equipment needed to access the Alarmas ABC XtremeK Application Service, and for paying all access charges (e.g., ISP, telecommunications) incurred while using the Alarmas ABC XtremeK Application Service. 
	(c) Upon your acceptance of this Agreement, Alarmas ABC will provide Customer with login access to the Alarmas ABC XtremeK Application Service for the term of the Agreement.
	2. License. Subject to the provisions of this Agreement, Alarmas ABC hereby grants to Customer a personal, nonexclusive, nonsublicensable, non-transferable, revocable license (the “License”) to use the Alarmas ABC XtremeK Application Service only in accordance with the applicable end user documentation related thereto (“Documentation”), if any, during the term of this Agreement. The License allows for Customer and any person authorized by Customer (collectively, “Users”) to access remotely and use (only through remote access) the object code version of the Alarmas ABC XtremeK Application Software by means of the Alarmas ABC website currently located at www.xtremek.com (the “Alarmas ABC Site”) for Customer’s personal use only and otherwise in accordance with this Agreement.
	3. Restrictions. Customer will not, and will not allow its Users, or agents to, directly or indirectly:
	(a) reverse assemble, reverse engineer, decompile or otherwise attempt to derive source code or underlying ideas or algorithms from the Alarmas ABC XtremeK Application Software or any component thereof;
	(b) copy, reproduce, modify, translate or create derivative works of, the Alarmas ABC XtremeK Application Service, Alarmas ABC XtremeK Application Software or any component thereof other than as expressly agreed to in this Agreement;
	(c) sell, lease, sublicense, market, distribute, assign or otherwise transfer rights to or commercially exploit in any way the Alarmas ABC XtremeK Application Service, Alarmas ABC XtremeK Application Software or any component thereof other than as expressly agreed to in this Agreement 
	(d) use, or permit the use of, the Alarmas ABC XtremeK Application Service or any component thereof to perform information processing or any other function whatsoever for any other person, entity or business including providing information processing for a third party in any service bureau, time sharing, lease, distribution, resale, rental, application service provider agreement or any other arrangement;
	(e) remove any proprietary, copyright, patent, trade mark, design right, trade secret, or any other proprietary rights legends from the Alarmas ABC Materials (as defined herein);
	(f) disclose or grant access to a User Access Code (as defined herein), the Alarmas ABC XtremeK Application Service or any component thereof to any third party other than one to whom Alarmas ABC has consented in writing; 
	(g) make more than one copy of the Documentation per User; or
	(h) use the Alarmas ABC XtremeK Application Service (i) for any unlawful, unsafe, malicious or abusive purpose, (ii) for interfering with others' use of the Service, (iii) in such a way as to defraud Alarmas ABC or any third party or (iv) to create damage or risk to Alarmas ABC business, network or facilities or to third parties.
	4. Member Account, Password and Security. To open an account for usage of the Alarmas ABC XtremeK Application Service, Customer must complete the registration process by providing Alarmas ABC with current, complete and accurate information as requested by Alarmas ABC. Inaccurate details may result in suspension or termination of the Alarmas ABC Application Service. Customer will also choose a password and an account name will be assigned. Customer is entirely responsible for maintaining confidentiality with regard to its password and account information. Furthermore, Customer is entirely responsible for any and all activities that occur under its account. Alarmas ABC will not be held liable for any third party claims and/or actions taken with respect to services offered. 
	5. Access to Alarmas ABC XtremeK Application Service. Customer shall access the Alarmas ABC Application Service by means of the browser that is recommended by Alarmas ABC and using equipment obtained by Customer as further described in Section 13 hereof. Customer shall access the Alarmas ABC XtremeK Application Service through the Alarmas ABC Site and by entering the appropriate access code (the “User Access Code”). User Access Codes will be generated. In all cases Customer shall assign record and control the use of the User Access Codes and will be solely responsible for any use thereof. For greater certainty, Alarmas ABC will not be responsible for the use or misuse of any User Access Code.
	6. Support Services. Alarmas ABC shall provide online support services (“Support Services”) to Customers through its Help Desk support program. The Help Desk support program allows Customer to access Support Services by calling its  telephone number (954-283-8399) or by sending an email to support@AlarmasABC.net Alarmas ABC shall not be required to provide Support Services: (a) to any person other than Customer and (b) in respect of any software other than the Alarmas ABC XtremeK Application Software.
	7. Fees. In consideration for providing the Services and the License, Customer shall pay to Alarmas ABC the fees set out in Schedule A (the “Fees”), without any set-off or deductions of any kind, as such Schedule may be amended from time to time in accordance with the terms hereof. Alarmas ABC shall have the right to increase the Fees at any time during the Term of this Agreement. The increase in the Fees shall be effective on the date stipulated in such notice.
	8. Fee Payment. Customer shall pay the Fees required hereunder in accordance with the payment requirements set forth in Schedule A. Amounts which have not been paid when due or in the event Alarmas ABC does not receive payment from Customer’s applicable credit card company, such amounts will be subject to a late payment charge at the rate of one and onehalf percent (1.5%) per month, payable monthly, on the amounts outstanding from the time such amounts become due until payment in full is received by Alarmas ABC. Any amount received by Alarmas ABC while late payment charges are outstanding will be applied first to interest owing.
	9. Taxes. Prices set out herein are exclusive of all taxes and Customer shall pay (and Alarmas ABC shall have no liability for), any taxes, tariffs, duties and other charges or assessments imposed or levied by any government or governmental agency in connection with this Agreement, including, without limitation, any federal, provincial, state and local sales, use, goods and services, value-added and personal property taxes on any payments due Alarmas ABC in connection with the Services provided hereunder, except for tax based solely on the net income of Alarmas ABC.
	10. Remedies in the Event of Failure to Pay. If Customer defaults in payment of any amount when due or any interest thereon, then Alarmas ABC may, in addition to any other rights or remedies at law or under this Agreement, and in its sole discretion, (i) suspend or deny Customer’s access to or use of the Service or the performance of any of its obligations under this Agreement until such failure is remedied, subject to such conditions as Alarmas ABC may require; and/or (ii) terminate this Agreement.
	11. Ownership of Intellectual Property. Customer acknowledges and agrees that Alarmas ABC shall retain and own all right, title and interest and all intellectual property rights (including copyrights, trade secrets, trademarks and patent rights) in and to the Alarmas ABC XtremeK Application Software, Documentation and the Alarmas ABC Site (collectively, the “Alarmas ABC Materials”) and all copies thereof, and that nothing herein transfers or conveys to Customer any ownership right, title or interest in or to the Alarmas ABC Materials or to any copy thereof or any license right with respect to same not expressly granted herein. Customer agrees that it will not, either during or after the termination of this Agreement, contest or challenge the ownership of the intellectual property rights in the Alarmas ABC Materials by Alarmas ABC.
	12. Ownership of Customer Data. Alarmas ABC acknowledges that all Customer data, including data transmitted by Customer to Alarmas ABC for processing using the Alarmas ABC XtremeK Application Service (“Customer Data”) and Customer systems used by Customer to access the Alarmas ABC Application Service shall be and remain the property of Customer. Alarmas ABC shall have the right to use and reproduce Customer Data solely to the extent necessary to provide the Services and fulfill its obligations to Customer hereunder.
	13. Access to Alarmas ABC XtremeK Application Service. Customer is responsible for obtaining all hardware, software and services which are necessary to connect to the Alarmas ABC Site and access the Services including all computers, web browsers, and services provided by an Internet service provider. All such facilities and services shall comply with Alarmas ABC interface specifications for the Services described in the Documentation or as otherwise required by Alarmas ABC.
	14. Member Privacy. It is Alarmas ABC policy to respect Customer’s privacy. Alarmas ABC will not monitor, edit, or disclose any personal information about Customer or Customer’s Alarmas ABC account, including its contents, without Customer’s prior permission unless Alarmas ABC has a good faith belief that such action is necessary to: (a) conform to legal requirements or comply with legal process; (b) protect and defend the rights or property of Alarmas ABC; (c) enforce this Agreement or protect Alarmas ABC business or reputation, including upon termination, cancellation or suspension of this Agreement by Alarmas ABC; (d) respond to request for identification in connection with claim of copyright or trademark infringement by Customer or a claim by a third party that Customer is using the Service in connection with an infringing, illegal or improper activity; or (e) act to protect the interests of Customer or others. Customer agrees that Alarmas ABC may access its account, including its contents, as stated above or to respond to service or technical issues.
	CUSTOMER HEREBY GRANTS ALARMAS ABC THE RIGHT TO SEND CUSTOMER COMMUNICATIONS VIA E-MAIL OF ANY UPDATES, UPGRADES, NOTICES, OR OTHER INFORMATION RELATING TO THE SERVICE THAT ALARMAS ABC DEEMS IMPORTANT FOR CUSTOMER TO KNOW. 
	15. Customer Security Responsibilities. To the extent deemed necessary by Customer, Customer shall implement security procedures necessary to limit access to the Service to Customer and any of Customer’s authorized Users. Customer shall notify Alarmas ABC immediately if there is a security breach or unauthorized use of the Service. Customer shall permit Alarmas ABC to review/audit Customer’s use of the Alarmas ABC XtremeK Application Software and the Alarmas ABC Application Service.
	16. Customer Data. Alarmas ABC will not be responsible or liable for any loss or damage to Customer’s Data or any inconvenience suffered by Customer or by any third person arising out of the use of the Service by Customer.
	17. Customer Systems. Alarmas ABC shall have no responsibility for the performance, adequacy, accuracy, concurrency or other matters related to Customer systems.
	18. Export. Customer agrees that it shall not export or re-export the Alarmas ABC XtremeK Application Software or any copies thereof, either directly or indirectly, outside of the jurisdiction in which Customer accesses such materials, except in compliance with all applicable laws, ordinances and regulations. Customer shall have the exclusive obligation to ensure that any export of the Alarmas ABC Application Software is in compliance with all applicable export laws and the laws of any foreign country.
	19. Provision of Releases. At its sole option, Alarmas ABC shall be entitled to prepare new versions of the Alarmas ABC XtremeK Application Software that Alarmas ABC generally makes available to Customers (“Update Releases”). Alarmas ABC exclusively shall determine whether Update Releases shall be included in the Alarmas ABC XtremeK Application Software provided pursuant to the Services. At any time, Alarmas ABC may install any Update Releases and use same to provide the Services.
	20. Right to Modify the Alarmas ABC XtremeK Application Service.  Alarmas ABC may from time to time, in its sole discretion, change some or all of the functionality or any component of the Alarmas ABC XtremeK Application Service or make any modification for the purpose of improving the performance, service quality, error correction or to maintain the competitiveness of the Service.
	21. Limited Warranty. Alarmas ABC warrants that the XtremeK Service will substantially conform to the related Documentation. For any breach of this warranty or the failure of Alarmas ABC to provide the Service as required herein (a “Deficiency”), Customer's sole and exclusive remedies and Alarmas ABC entire obligations to Customer, any User or any other person or entity hereunder shall be, at Alarmas ABC election, for Alarmas ABC to (i) provide the Services that are the subject of the Deficiency or (ii) refund to Customer the fees paid to Alarmas ABC in the calendar year in respect of which the cause of action first arose. The remedies in this Section 21 are Customer’s sole and exclusive remedy for any breach or alleged breach of any warranty to Customer and are expressly in lieu of any or all other remedies which may be available to Customer resulting from the furnishing, the failure to furnish or the quality of any Service. Alarmas ABC does not warrant the accuracy of any data or information furnished to Customer that is created from Customer Data, Customer systems or software supplied by Customer.
	22. Warranty Disclaimer. 
	(a) EXCEPT AS EXPRESSLY PROVIDED HEREIN, Alarmas ABC EXPRESSLY DISCLAIMS ANY AND ALL REPRESENTATIONS, WARRANTIES AND CONDITIONS OF ANY KIND OR NATURE, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, REPRESENTATIONS, WARRANTIES AND CONDITIONS OF SATISFACTORY QUALITY, PERFORMANCE, MERCHANTABILITY, MERCHANTABLE QUALITY, DURABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND THOSE ARISING BY STATUTE OR OTHERWISE IN LAW OR FROM A COURSE OF DEALING OR USE OF TRADE. CUSTOMER ACKNOWLEDGES AND AGREES THAT THE LICENSORS AND SUPPLIERS OF ALARMAS ABC MAKE NO DIRECT WARRANTY OF ANY KIND TO CUSTOMER UNDER THIS AGREEMENT.
	(b) ALARMAS ABC DOES NOT REPRESENT OR WARRANT THAT: (i) THE SERVICES WILL MEET CUSTOMER'S REQUIREMENTS; (ii) THE SERVICES WILL BE ERROR-FREE OR UNINTERRUPTED OR THAT THE RESULTS OBTAINED FROM THEIR USE WILL BE ACCURATE OR RELIABLE; OR (iii) ALL DEFICIENCIES IN THE SERVICES CAN BE FOUND OR CORRECTED. FURTHER, THE SERVICE MAY BE INTERRUPTED OR UNAVAILABLE FOR THE PURPOSES OF PERFORMING MAINTENANCE OR UPGRADES. ALARMAS ABC WILL NOT BE RESPONSIBLE FOR: (a) SERVICE IMPAIRMENTS CAUSED BY ACTS WITHIN THE CONTROL OF CUSTOMER OR ANY USER; (b) INTEROPERABILITY OF SPECIFIC CUSTOMER APPLICATIONS OR EQUIPMENT; (c) INABILITY OF CUSTOMER TO ACCESS OR INTERACT WITH ANY OTHER SERVICE PROVIDER THROUGH THE INTERNET, OTHER NETWORKS OR USERS THAT COMPRISE THE INTERNET OR THE INFORMATIONAL OR COMPUTING RESOURCES AVAILABLE THROUGH THE INTERNET; (d) INTERACTION WITH OTHER SERVICE PROVIDERS, NETWORKS, USERS OR INFORMATIONAL OR COMPUTING RESOURCES THROUGH THE INTERNET; (e) SERVICE PROVIDED BY OTHER SERVICE PROVIDERS; OR (f) PERFORMANCE IMPAIRMENTS CAUSED ELSEWHERE ON THE INTERNET.
	23. Limit of Liability.  
	(a) FOR ANY BREACH OR DEFAULT BY ALARMAS ABC OF ANY OF THE PROVISIONS OF THIS AGREEMENT, OR WITH RESPECT TO ANY CLAIM ARISING HEREFROM OR RELATED HERETO, ALARMAS ABC's ENTIRE LIABILITY SHALL IN NO EVENT EXCEED THE LESSER OF THE FOLLOWING: (i) THE FEES PAID TO ALARMAS ABC BY CUSTOMER PURSUANT TO THIS AGREEMENT IN THE CALENDAR YEAR IN RESPECT OF WHICH THE CAUSE OF ACTION FIRST AROSE EVEN IF THE CAUSE OF ACTION IS A CONTINUING ONE, OR (ii) IN THE AGGREGATE WITH RESPECT TO ALL CLAIMS MADE UNDER OR RELATED TO THIS AGREEMENT, THE AMOUNT PAID BY CUSTOMER UNDER THIS AGREEMENT. 
	(b) IN NO EVENT WILL ALARMAS ABC BE LIABLE FOR DIRECT, SPECIAL, INCIDENTAL, INDIRECT, OR CONSEQUENTIAL LOSS OR DAMAGE, LOST BUSINESS REVENUE, LOSS OF PROFITS, LOSS OF DATA, LOSS OF COVER, DAMAGES FOR DELAY, PUNITIVE OR EXEMPLARY DAMAGES, FAILURE TO REALIZE EXPECTED PROFITS OR SAVINGS OR ANY CLAIM AGAINST CUSTOMER BY ANY OTHER PERSON, EVEN IF ALARMAS ABC HAS BEEN ADVISED OF THE POSSIBILITY OF ANY SUCH LOSSES OR DAMAGES.
	(c) ALARMAS ABC SHALL NOT BE LIABLE FOR UNAUTHORIZED ACCESS TO OR ALTERATION, THEFT, LOSS OR DESTRUCTION OF ANY DATA, EQUIPMENT OR THE SERVICES, INCLUDING THROUGH ACCIDENT, FRAUDULENT MEANS OR DEVICES, OR ANY OTHER METHOD.
	(d) ALARMAS ABC SHALL BE LIABLE TO CUSTOMER ONLY AS EXPRESSLY PROVIDED IN THIS AGREEMENT BUT SHALL HAVE NO OTHER OBLIGATION, DUTY, OR LIABILITY WHATSOEVER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE TO CUSTOMER. THE LIMITATIONS, EXCLUSIONS AND DISCLAIMERS IN THIS AGREEMENT SHALL APPLY IRRESPECTIVE OF THE NATURE OF THE CAUSE OF ACTION, DEMAND, OR ACTION BY CUSTOMER, INCLUDING BREACH OF CONTRACT, NEGLIGENCE, TORT, OR ANY OTHER LEGAL THEORY AND SHALL SURVIVE A FUNDAMENTAL BREACH OR BREACHES OR THE FAILURE OF THE ESSENTIAL PURPOSE OF THIS AGREEMENT OR OF ANY REMEDY CONTAINED HEREIN. SOME STATES AND JURISDICTIONS DO NOT ALLOW LIMITATIONS ON DURATION OR THE EXCLUSION OF AN IMPLIED WARRANTY, SO THE ABOVE LIMITATION MAY NOT APPLY TO YOU. YOU MAY ALSO HAVE ADDITIONAL RIGHTS NOT STATED IN THIS DOCUMENT.
	(e) Neither party shall be responsible or liable for any loss, damage or inconvenience suffered by the other or by any third person, to the extent that such loss, damage or inconvenience is caused by the failure of the other party to comply with its obligations under this Agreement.
	(f) Neither party may bring an action, regardless of form, arising out of or related to this Agreement (other than to recover fees or expenses due to Alarmas ABC) more than one year after the cause of action has arisen or the date of discovery of such cause, whichever is later.
	(g) Customer agrees to indemnify and hold Alarmas ABC, its affiliates, employees, officers, directors and shareholders harmless from and against any claims, suits, actions or proceedings (“Claims”) brought and damages, costs (including attorney’s fees) or judgments awarded against Alarmas ABC that arise from or in connection with: (i) Claims by any person or entity to the extent that such Claims are based upon or arise out of Customer’s use of the Services or Customer’s actions; (ii) breach by Customer of this Agreement; or (iii) Customer’s failure to comply with all applicable laws. Alarmas ABC shall give Customer prompt written notice of such Claims, permit Customer to defend (with counsel reasonably acceptable to Alarmas ABC) and/or settle such Claims (upon terms reasonably acceptable to Alarmas ABC), and give Customer all information and assistance reasonably requested by Customer in connection with such Claims.
	24. Term of Agreement. This Agreement and the License granted herein shall continue during the applicable Service period chosen by Customer as indicated on Schedule A, unless terminated in accordance with the provisions hereof.
	25. Termination. 
	(a) This Agreement may be terminated or Service suspended by Alarmas ABC (i) if Customer fails to make any payment when due or any interest thereon to Alarmas ABC, or (ii) immediately, without notice or liability to Alarmas ABC, in the event of a breach by Customer of any of Customer’s obligations under this Agreement.
	(b) by either party providing the other party with (30) days advance written notice of its intent to terminate;
	(c) by either party in the event the other party materially breaches any of its duties, obligations or responsibilities under this Agreement (other than breaches covered in Section 25(a) hereof), and fails to cure such breach or provide the other party with an acceptable plan for curing such breach within thirty (30) days after receipt by the breaching party of written notice specifying the breach; or
	(d) by either party in the event: (i) a receiver, trustee, administrator, or administrative receiver is appointed for the other party or its property; (ii) the other party makes an assignment for the benefit of creditors; (iii) any proceedings should be commenced against the other party under any bankruptcy, insolvency, or debtor’s relief law, and such proceedings shall not be vacated or set aside within thirty (30) days from the date of commencement thereof; or (iv) the other party is liquidated or dissolved.
	26. Effect of Termination. Except to the extent agreed to in writing by the parties, upon the termination of this Agreement:
	(a) Alarmas ABC shall be entitled to immediately cease providing the Services;
	(b) Alarmas ABC shall be entitled to immediately terminate Customer’s access to the Alarmas ABC Application Service;
	(c) Customer shall forthwith pay to Alarmas ABC all amounts owing under this Agreement as of the date of termination;
	(d) if this Agreement is terminated by Customer under Section 25(b) or 25(c) above and Customer has subscribed for the Annual Service Plan and paid fees for twelve (12) months in advance, Alarmas ABC shall refund to Customer an amount equal to the difference between (i) the twelve months’ fees already paid, and (ii) the product of (x) number of complete calendar months remaining in the Term and (y) the monthly Service fee as set forth on Schedule A, less $100 and any other fees that may be due and owing to Alarmas ABC by Customer;
	(e) if this Agreement is terminated by Alarmas ABC under Section 25(a), 25(c) or 25(d), all amounts that would have become due under this Agreement shall automatically accelerate and become immediately due and payable by Customer to Alarmas ABC;
	(f) Alarmas ABC shall have no obligation to refund any amounts to Customer
	(g) Customer shall, and shall cause its Users to, immediately and permanently cease to use, in any manner whatsoever, the Alarmas ABC Application Service, the User Access Codes and the Documentation; and
	(h) The License granted under Section 3 will automatically terminate.
	27. Survival. The parties hereto agree that the provisions hereof requiring performance or fulfillment after the expiry or earlier termination of this Agreement shall survive such expiry or earlier termination. The provisions of this Agreement that by their nature are intended to survive the expiration or earlier termination, including, without limitation, those provisions relating to ownership, confidential information, warranty disclaimer, and limits of liability shall survive the expiration or earlier termination of this Agreement.
	28. Wireless Service.  Customer acknowledges and agrees that the Product and Service use industry standard cellular wireless communications services to communicate with vehicles.  Therefore, vehicles must be within cellular coverage to communicate.  Customer further acknowledges and agrees that Alarmas ABC is not the underlying wireless carrier and that Alarmas ABC may contract with various wireless carriers from time to time.  Accordingly, UNDER NO CIRCUMSTANCES SHALL ALARMAS ABC BE LIABLE TO CUSTOMER OR ANY OTHER PERSON OR ENTITY FOR ANY LOSS, INJURY OR DAMAGE, OF WHATEVER KIND OR NATURE, RESULTING FROM OR ARISING OUT OF ANY MISTAKES, ERRORS, OMISSIONS, DELAYS OR INTERRUPTIONS IN THE RECEIPT, TRANSMISSION OR STORAGE OF ANY MESSAGES, SIGNALS OR INFORMATION ARISING OUT OF OR IN CONNECTION WITH THE SERVICES OR USE OF ANY UNDERLYING CARRIER'S WIRELESS NETWORK.    Additionally, Customer acknowledges and agrees:
	(a) CUSTOMER HAS NO CONTRACTUAL RELATIONSHIP WITH THE UNDERLYING WIRELESS SERVICE CARRIER AND CUSTOMER IS NOT A THIRD PARTY BENEFICIARY OF ANY AGREEMENT BETWEEN ALARMAS ABC AND ANY SUCH UNDERLYING CARRIER.  CUSTOMER UNDERSTANDS AND AGREES THAT THE UNDERLYING CARRIER SHALL HAVE NO LEGAL, EQUITABLE, OR OTHER LIABILITY OF ANY KIND TO CUSTOMER.  IN ANY EVENT, REGARDLESS OF THE FORM OF THE ACTION, WHETHER FOR BREACH OF CONTRACT, WARRANTY, NEGLIGENCE, STRICT LIABILITY IN TORT OR OTHERWISE, CUSTOMER’S EXCLUSIVE REMEDY FROM ANY SUCH UNDERLYING CARRIER FOR CLAIMS ARISING IN ANY WAY IN CONNECTION WITH THIS AGREEMENT, FOR ANY CAUSE WHATSOEVER, INCLUDING, BUT NOT LIMITED TO, ANY FAILURE OR DISRUPTION OF SERVICE PROVIDED HEREUNDER, IS LIMITED TO PAYMENT OF DAMAGES IN AN AMOUNT NOT TO EXCEED THE AMOUNT PAID BY CUSTOMER FOR THE SERVICES DURING THE TWO (2)-MONTH PERIOD PRECEDING THE DATE THE CLAIM AROSE.
	(b) CUSTOMER SHALL INDEMNIFY AND HOLD HARMLESS ALARMAS ABC  AND THE UNDERLYING WIRELESS SERVICE CARRIER AND ITS OFFICERS, EMPLOYEES, AND AGENTS AGAINST ANY AND ALL CLAIMS, INCLUDING WITHOUT LIMITATION CLAIMS FOR LIBEL, SLANDER, OR ANY PROPERTY DAMAGE, PERSONAL INJURY OR DEATH, ARISING IN ANY WAY, DIRECTLY OR INDIRECTLY, IN CONNECTION WITH THIS AGREEMENT OR THE USE, FAILURE TO USE, OR INABILITY TO USE THE NUMBER EXCEPT WHERE THE CLAIMS RESULT FROM THE UNDERLYING CARRIER’S GROSS NEGLIGENCE OR WILLFUL MISCONDUCT.  THIS INDEMNITY SHALL SURVIVE THE TERMINATION OF THE AGREEMENT.
	(c) CUSTOMER HAS NO PROPERTY RIGHT IN ANY NUMBER ASSIGNED TO IT, AND UNDERSTANDS THAT ANY SUCH NUMBER CAN BE CHANGED FROM TIME TO TIME.
	(d) CUSTOMER UNDERSTANDS THAT ALARMAS ABC AND THE UNDERLYING CARRIER CANNOT GUARANTY THE SECURITY OF WIRELESS TRANSMISSIONS, AND WILL NOT BE LIABLE FOR ANY LACK OF SECURITY RELATING TO THE USE OF THE SERVICES.
	(e) THE SERVICE IS FOR CUSTOMER’S USE ONLY AND CUSTOMER MAY NOT RESELL THE SERVICE TO ANY OTHER PARTY.  
	30. General.
	(a) Notice. Alarmas ABC may give notice by means of a general notice through the Service, electronic mail to Customer’s e-mail address on record in Alarmas ABC account information, or by written communication sent by first class mail to Customer’s address on record in Alarmas ABC account information. Customer may give notice to Alarmas ABC at any time by any of the following: electronic mail to support@AlarmasABC.net; letter sent by confirmed facsimile to Alarmas ABC at the following fax number: (954)543-6146, Attention: Alarmas ABC Customer Care; letter delivered by nationally recognized overnight delivery service to Alarmas ABC at the following address: Alarmas ABC , 1280 S Powerline Road, Suite 5, Pompano Beach, FL 33069, Attention: Alarmas ABC Customer Care, with a copy to the Legal Department.
	(b) Force Majeure. If the performance of this Agreement, or any obligation there under except the making of payments hereunder is prevented, restricted, or interfered with by reason of: fire, flood, earthquake, explosion or other casualty or accident or act of God; strikes or labor disputes; inability to procure or obtain delivery of parts, supplies, power, telecommunication services, equipment or software from suppliers; war or other violence; any law, order proclamation, regulation, ordinance, demand or requirement of any governmental authority; or any other act or condition whatsoever beyond the reasonable control of the affected party, the party so affected shall be excused from such performance to the extent of such prevention, restriction or interference; provided, however, that the party so affected shall take reasonable steps to avoid or remove such cause of non-performance and shall promptly resume performance hereunder whenever such causes are removed.
	(c) Customer Rights. Nothing in this Agreement shall create or vest in Customer any right, title, or interest in the Alarmas ABC XtremeK Application Service or the Alarmas ABC Materials other than the limited right to use the Service under the terms and conditions of this Agreement. All such rights shall remain in Alarmas ABC.
	(d) Severability. To the extent that any provision, portion or extent of this Agreement is deemed to be invalid, illegal or unenforceable, such provision, portion or extent shall be severed and deleted or limited so as to give effect to the intent of the parties insofar as possible and the remainder of this Agreement, as the case may be, shall remain binding upon the parties.
	(e) Assignment. Customer may not, without Alarmas ABC's prior written consent, assign or transfer this agreement or any of its rights or obligations under this Agreement to any third person (an “Assignee”).  Alarmas ABC may assign this Agreement to any person or entity without the consent of Customer. Alarmas ABC may delegate to affiliates of Alarmas ABC and to agents, suppliers and contractors of Alarmas ABC any of the obligations herein imposed upon Alarmas ABC and Alarmas ABC may disclose to any such persons any information required by them to perform the duties so delegated to them.
	(f) Waiver and Amendment. Alarmas ABC reserves the right to change the terms and conditions of this Agreement or its policies relating to the Service at any time.  Continued use of the Service for more than thirty (30) days after any such change shall constitute your consent to such changes. 
	(g) Governing Law; Venue. This Agreement shall be governed by and construed in accordance with the laws of the State of Florida without reference to conflict or choice of law rules or principles. The parties irrevocably and unconditionally submit to the exclusive jurisdiction of the court of the State of Florida located in Broward County or in the United States District Court for the Southern District of Florida for the purposes of any suit, action or other proceeding arising out of this Agreement or the subject matter hereof brought by any party hereto; and (b) hereby waive and agree not to assert as a defense or otherwise, in any such suit action or proceeding, any claim that it is not subject personally to the jurisdiction of the above-named courts, that its property is exempt or immune from attachment or execution, that the suit, action or proceeding is brought in an inconvenient forum, that the venue of the suit, action or proceeding is improper or that this Agreement or the subject matter hereof may not be enforced by such court. 
	(h) Construction. The titles of the sections of this Agreement are for convenience of reference only and are not to be considered in construing this Agreement. Unless the context of this Agreement clearly requires otherwise: (i) references to the plural include the singular, the singular the plural, and the part the whole, (ii) references to one gender include all genders, (iii) “or” has the inclusive meaning frequently identified with the phrase “and/or,” (iv) “including” has the inclusive meaning frequently identified with the phrase “including but not limited to” or “including without limitation,” and (v) references to “hereunder,” “herein” or “hereof” relate to this Agreement as a whole. Any reference in this Agreement to any statute, rule, regulation or agreement, including this Agreement, shall be deemed to include such statute, rule, regulation or agreement as it may be modified, varied, amended or supplemented from time to time. The parties agree that this Agreement shall be fairly interpreted in accordance with its terms without any strict construction in favor of or against either party and that ambiguities shall not be interpreted against the drafting party.
	(i) Attorneys’ Fees.  If any legal action is necessary in order to enforce any of the terms of this Agreement or the relationship between Customer and Alarmas ABC, the prevailing party in any such action shall be entitled to recover its reasonable attorneys' fees and costs from the non-prevailing party.
	 
	(j) Entire Agreement.  This Agreement sets forth the entire understanding and supersedes prior agreements between the parties relating to the subject matter contained herein and merges all prior discussions between them, and neither party shall be bound by any definition, condition, provision, representation, warranty, covenant or promise other than as expressly stated in this Agreement or as it contemporaneously or subsequently set forth in writing and executed by a duly authorized officer or representative of the party to be bound thereby.
	 Schedule A
	A.	Payment Plan Options.  Customer has the option to: 
	 (i)	Monthly Service Plan.  Subscribe to a Monthly Service Plan in which Customer shall pay Alarmas ABC a monthly service fee of $14.99 per month plus applicable taxes and subscribe to the Service for a period of not less than Twelve (12) months after Customer’s acceptance of this Agreement.  If Customer elects this Monthly Service Plan, Customer shall pay Alarmas ABC one month’s service fee simultaneous with Customer’s acceptance of this Agreement and an additional monthly service fee each thirty days thereafter.  The Monthly Service Plan shall automatically renew for successive additional twelve month periods upon the expiration of the initial Monthly Service Plan and each renewal Monthly Service Plan unless either party provides the other party with not less than thirty days’ prior written notice indicating its desire to terminate this Agreement; or
	 (ii) Annual Service Plan.  Subscribe to an Annual Service Plan in which Customer shall pay Alarmas ABC an annual service fee of $144.00 plus applicable taxes ($12.00 multiplied by twelve plus applicable taxes) simultaneous with the execution of this Agreement and receive the Services for a period of Fourteen (14) months after Customer’s acceptance of this Agreement.  The Annual Service Plan shall automatically renew for successive additional Fourteen (14) month periods upon the expiration of the initial Annual Service Plan and each renewal Annual Service Plan unless either party provides the other party with not less than thirty days’ prior written notice indicating its desire to terminate this Agreement.
	B. Conditions of Sale and Payment Terms. To purchase the Alarmas ABC Application Services, Customer must (a) be at least eighteen (18) years of age or the applicable state age of majority, (b) be a natural person (or corporations, partnerships or other legal entities), and (c) be a resident in the 50 states of the United States of America and Canada inclusive of its commonwealths, territories and possessions. Prior to the purchase of any Alarmas ABC XtremeK Application Services,  Customer  must provide Alarmas ABC with a valid credit card number and associated payment information including all of the following: (i) Customer’s name as it appears on the card, (ii) Customer’s billing address on file with its credit card company, (iii) Customer’s credit card number, (iv) the credit card type, (v) the date of expiration, (vi) any activation numbers or codes needed to charge the card and (vii) any other information requested by Alarmas ABC. By submitting that information to Alarmas ABC, Customer hereby agrees that Customer authorizes Alarmas ABC to charge Customer’s card as may be required for Customer to pay Alarmas ABC all amounts that may be due to Alarmas ABC under this Agreement. All sales of Alarmas ABC Application Services are final. All charges from those sales are nonrefundable.
	C. Methods of Payment, Credit Card Terms and Taxes. All payments must be made by VISA, MasterCard, Discover, or AMEX (any of which may be removed by Alarmas ABC in its sole discretion). Unless expressly agreed in writing by Alarmas ABC, Alarmas ABC does not accept any other payment form. If Alarmas ABC offers or accepts any other form of payment, Customer hereby agrees to all restrictions, terms and conditions associated with such additional form of payment as required by Alarmas ABC. Customer’s card issuer agreement governs Customer’s use of his or her designated card, and Customer must refer to that agreement and not this Agreement to determine Customer’s rights and liabilities as a cardholder. CUSTOMER, AND NOT ALARMAS ABC, IS RESPONSIBLE FOR PAYING ANY UNAUTHORIZED AMOUNTS BILLED TO CUSTOMER’S CREDIT CARD BY A THIRD PARTY. Customer agrees to pay all fees and charges incurred in connection with Customer’s purchases (including any applicable taxes) at the rates in effect when the charges were incurred. Unless Customer notifies Alarmas ABC of any discrepancies within sixty (60) days after they first appear on Customer’s credit card statement, Customer agrees that such charges shall be deemed accepted by Customer for all purposes. If Alarmas ABC does not receive payment from Customer’s credit card issuer or its agent, Customer agrees to pay all amounts due upon demand by Alarmas ABC. Customer is responsible for paying any governmental taxes imposed on Customer’s purchases, including, but not limited to, sales, use or value-added taxes. 
			
				</textarea>

 			</div>

			<br/><br/>

			<div class="form_link">
				<a href="Login.aspx" ><< Return to Login Page</a>
			</div>

			<br/>

			<div class="form_footer"></div> 
		</div>
	</div>
    </form>
</body>
</html>
